CREATE TABLE "group" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "gid" VARCHAR);
CREATE TABLE "payment" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "uid" VARCHAR, "date" DATETIME, "verified" BOOL, "status" INTEGER);
CREATE TABLE "preferences" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "uidNumber" INTEGER, "last_change" DATETIME, "key" VARCHAR, "value" VARCHAR);
CREATE TABLE "tmpMember" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "gn" VARCHAR, "sn" VARCHAR, "homePostalAddress" VARCHAR, "phone" VARCHAR, "mobile" VARCHAR, "mail" VARCHAR, "xmppID" VARCHAR);
